WITH tesseract_services AS (
    SELECT * FROM {{ source('tesseract', 'airbyte_scser')}} 
),

final AS (
    SELECT
        ts.ser_area_code as area_code,
        ts.ser_call_count as call_count,
        ts.ser_calt_code as calt_code,
        ts.ser_cont_num as cont_number,
        ts.ser_cont_start_date::date as cont_start_date,
        ts.ser_cont_term_date::date as contract_term_date,
        ts.ser_contract_flag as contract_flag,
        ts.ser_cover_code as cover_code,
        ts.ser_cust_owned_flag as cust_owned_flag,
        ts.ser_delivery_date::date as delivery_date,
        ts.ser_install_date::date as install_date,
        ts.ser_lab_war_end_date::date as lab_war_end_date,
        ts.ser_lab_war_start_date::date as lab_war_start_date,
        ts.ser_last_call_cdate::date as last_call_cdate,
        ts.ser_last_call_num as last_call_number,
        ts.ser_last_employ_num as last_employ_number,
        ts.ser_last_update::timestamp as last_update,
        ts.ser_loc as loc,
        ts.ser_mc_cycle_unit as mc_cycle_unit,
        ts.ser_memo as memo,
        ts.ser_meter_count as meter_count,
        ts.ser_meter_date::date as meter_date,
        ts.ser_mmc as mmc,
        ts.ser_next_pm_date as next_pm_date,
        ts.ser_num as service_number,
        ts.ser_on_hold_flag as on_hold_flag,
        ts.ser_pm_cycle as pm_cycle,
        ts.ser_pm_cycle_unit as pm_cycle_unit,
        ts.ser_pm_time as pm_time,
        ts.ser_pm_usage_cycle as pm_usage_cycle,
        ts.ser_prod_num as product_number,
        ts.ser_qty as quantity,
        ts.ser_ref_b1 as ref_b1,
        ts.ser_ref_b2 as ref_b2,
        ts.ser_reference_1 as reference_1,
        ts.ser_reference_2 as reference_2,
        ts.ser_reference_4 as reference_4,
        ts.ser_reference_5 as reference_5,
        ts.ser_reference_6 as reference_6,
        ts.ser_reference_7 as reference_7,
        ts.ser_reference_8 as reference_8,
        ts.ser_sestat_code as sestat_code,
        CAST(ts.ser_sestat_end_date as DATE) as sestat_end_date,
        CAST(ts.ser_sestat_start_date as DATE) as sestat_start_date,
        ts.ser_site_num as site_number,
        CAST(ts.ser_supp_lab_war_end_date as DATE) as supp_lab_war_end_date,
        CAST(ts.ser_supp_lab_war_start_date as DATE) as supp_lab_war_start_date,
        ts.ser_supp_war_end_date as supp_war_end_date,
        CAST(ts.ser_supp_war_start_date as DATE) as supp_war_start_date,
        ts.ser_suppcont_num as support_contract_number,
        ts.ser_system_num as system_number,
        ts.ser_war_disc as war_disc,
        CAST(ts.ser_war_end_date as DATE) as war_end_date,
        ts.ser_war_part_billable as war_part_billable,
        ts.ser_war_start_date as war_start_time,
        ts.ser_war_time_billable as war_time_billable
    FROM tesseract_services ts
)

-- Select * from Final CTE
SELECT * FROM final