{% macro get_model_range(model_number) %}
    CASE 
        WHEN UPPER({{model_number}}) LIKE 'E2S-HP%' THEN 'E2S-HP'
        WHEN UPPER({{model_number}}) LIKE 'E2S%' THEN 'E2S'
        WHEN UPPER({{model_number}}) LIKE 'E1S%' THEN 'E1S'
        WHEN UPPER({{model_number}}) LIKE 'M401%' THEN 'M401'
        WHEN UPPER({{model_number}}) LIKE 'M402%' THEN 'M402'
        WHEN UPPER({{model_number}}) LIKE 'M403%' THEN 'M403'
        WHEN UPPER({{model_number}}) LIKE 'E401%' THEN 'E401'
        WHEN UPPER({{model_number}}) LIKE 'E402%' THEN 'E402'
        WHEN UPPER({{model_number}}) LIKE 'E403%' THEN 'E403'
        WHEN UPPER({{model_number}}) LIKE 'M501%' THEN 'M501'
        WHEN UPPER({{model_number}}) LIKE 'E501%' THEN 'E501'
        WHEN UPPER({{model_number}}) LIKE 'E503%' THEN 'E503'
        WHEN UPPER({{model_number}}) LIKE 'X12-HP%' THEN 'X12-HP'
        WHEN UPPER({{model_number}}) LIKE 'X16%' THEN 'X16'
        WHEN UPPER({{model_number}}) LIKE 'X12%' THEN 'X12'
        WHEN UPPER({{model_number}}) LIKE '12E%' THEN '12E'
        WHEN UPPER({{model_number}}) LIKE 'E1%' THEN 'E1'
        WHEN UPPER({{model_number}}) LIKE 'E2%' THEN 'E2'
        WHEN UPPER({{model_number}}) LIKE 'E4S%' THEN 'E4S'
        WHEN UPPER({{model_number}}) LIKE 'E4C%' THEN 'E4C'
        WHEN UPPER({{model_number}}) LIKE 'E4%' THEN 'E4'
        WHEN UPPER({{model_number}}) LIKE 'E5%' THEN 'E5'
        WHEN UPPER({{model_number}}) LIKE 'E6%' THEN 'E6'
        WHEN UPPER({{model_number}}) LIKE 'E3%' THEN 'E3'
        WHEN UPPER({{model_number}}) LIKE 'MDM%' THEN 'MDM'
        WHEN UPPER({{model_number}}) LIKE 'MD%' THEN 'MD'
        WHEN UPPER({{model_number}}) LIKE 'HD%' THEN 'HD'
        WHEN UPPER({{model_number}}) LIKE '1925%' THEN 'HD'
        WHEN UPPER({{model_number}}) LIKE '1725%' THEN 'HD'
        ELSE 'Other'
    END
{% endmacro %}


